# Generated by Django 6.0.6 on 2026-07-09 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=255)),
                ('nivel_risco', models.IntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto'), (4, 'Crítico')], default=1)),
                ('eventos', models.IntegerField(default=0)),
                ('ultimo_evento', models.DateTimeField(blank=True, null=True)),
                ('coordenadas', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=255)),
                ('url_rtsp', models.URLField(blank=True, max_length=500, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=255)),
                ('coordenadas', models.JSONField(default=dict)),
                ('populacao_estimada', models.IntegerField(default=0)),
                ('numero_residencias', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('roubo_residencia', 'Roubo a Residência'), ('roubo_veiculo', 'Roubo de Veículo'), ('assalto_pessoa', 'Assalto a Pessoa'), ('furto', 'Furto'), ('vandalismo', 'Vandalismo'), ('violencia_domestica', 'Violência Doméstica'), ('trafico_drogas', 'Tráfico de Drogas'), ('homicidio', 'Homicídio'), ('outro', 'Outro')], max_length=30)),
                ('descricao', models.TextField()),
                ('data_ocorrencia', models.DateTimeField()),
                ('localizacao', models.CharField(max_length=255)),
                ('coordenadas', models.JSONField(default=dict)),
                ('vitima', models.CharField(blank=True, max_length=100, null=True)),
                ('suspeito', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comunidade')),
                ('registado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstrategiaSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('policia_comunitaria', 'Polícia Comunitária'), ('vigilancia_vizinhos', 'Vigilância Rotativa entre Vizinhos'), ('camera_seguranca', 'Câmaras de Segurança'), ('iluminacao', 'Iluminação Pública'), ('alarme', 'Sistemas de Alarme'), ('guarda_patrimonial', 'Guarda Patrimonial'), ('grupo_whatsapp', 'Grupo de WhatsApp'), ('patrulha_voluntaria', 'Patrulha Voluntária'), ('outro', 'Outro')], max_length=30)),
                ('descricao', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('data_implementacao', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('movimento', 'Movimento Detectado'), ('porta_aberta', 'Porta Aberta'), ('janela_aberta', 'Janela Aberta'), ('alarme', 'Alarme Disparado'), ('face_detectada', 'Face Detectada'), ('comportamento_suspeito', 'Comportamento Suspeito')], max_length=30)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
                ('alerta_enviado', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=10)),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventoseguranca')),
            ],
        ),
        migrations.CreateModel(
            name='PercepcaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_seguranca', models.IntegerField(choices=[(1, 'Muito Inseguro'), (2, 'Inseguro'), (3, 'Neutro'), (4, 'Seguro'), (5, 'Muito Seguro')])),
                ('principais_medos', models.TextField()),
                ('sugestoes', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('prefiro_nao_dizer', 'Prefiro não dizer')], max_length=20, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=30, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('nuit', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('email_comunicacao', models.BooleanField(default=True)),
                ('whatsapp', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('push_notification', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('cancelado', 'Cancelado'), ('em_analise', 'Em Análise')], default='ativo', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('indicacoes', models.IntegerField(default=0)),
                ('codigo_2fa', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo_2fa', models.BooleanField(default=False)),
                ('codigos_recuperacao', models.JSONField(blank=True, default=list)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioComunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('pir', 'PIR'), ('ultrassom', 'Ultrassom'), ('laser', 'Laser')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_evento', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventoseguranca',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sensormovimento'),
        ),
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativas', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('ultima_tentativa', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
