# Generated by Django 6.0.6 on 2026-07-10 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=5)),
                ('taxa_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_2fa', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo_2fa', models.BooleanField(default=False)),
                ('codigos_recuperacao', models.JSONField(blank=True, default=list)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('prefiro_nao_dizer', 'Prefiro não dizer')], max_length=20, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=30, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('nuit', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('email_comunicacao', models.BooleanField(default=True)),
                ('whatsapp', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('push_notification', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('cancelado', 'Cancelado'), ('em_analise', 'Em Análise')], default='ativo', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('indicacoes', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaMoeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('moeda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moeda')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_moeda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativas', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('ultima_tentativa', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
