# Generated by Django 6.0.6 on 2026-07-12 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaocompra',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicaocompra',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisicaocompra',
            name='data_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicaocompra',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requisicaocompra',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisicaocompra',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisicaocompra',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Analise'), ('encontrado', 'Fornecedor Encontrado'), ('em_negociacao', 'Em Negociacao'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisicaocompra',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requisicaocompra',
            name='valor_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comissao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_fornecedor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('codigo_confirmacao', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_cliente', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_fornecedor', to=settings.AUTH_USER_MODEL)),
                ('requisicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.requisicaocompra')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.transacao')),
            ],
        ),
    ]
