# Generated by Django 6.0.6 on 2026-07-09 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200)),
                ('nif', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('coordenadas', models.JSONField(default=dict)),
                ('raio_atuacao', models.IntegerField(default=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=True)),
                ('avaliacao_media', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(related_name='fornecedores', to='core.categoria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=255)),
                ('coordenadas', models.JSONField(default=dict)),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto - À espera de fornecedor'), ('em_negociacao', 'Em Negociação'), ('aceite', 'Aceite pelo fornecedor'), ('pago', 'Pago - Em Escrow'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('fornecedor_escolhido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('disponivel', models.BooleanField(default=True)),
                ('registado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_fornecedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Pagamento'), ('pago', 'Pago - Em Escrow'), ('entregue', 'Entregue - Aguardando Confirmação'), ('confirmado', 'Confirmado - Pagamento Libertado'), ('reembolsado', 'Reembolsado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('codigo_confirmacao', models.CharField(blank=True, max_length=6, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('data_reembolso', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transacao', to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='core.transacao')),
            ],
        ),
    ]
