# Generated by Django 6.0.6 on 2026-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaocompra',
            name='ano',
            field=models.IntegerField(blank=True, help_text='Ex: 2025', null=True),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='condicao',
            field=models.CharField(blank=True, choices=[('novo', 'Novo'), ('usado', 'Usado'), ('seminovo', 'Seminovo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='marca',
            field=models.CharField(blank=True, help_text='Ex: Toyota', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='modelo',
            field=models.CharField(blank=True, help_text='Ex: Fortuner', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
