# Generated by Django 6.0.6 on 2026-07-13 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transacaompesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='total_avaliacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('cancelado', 'Cancelado'), ('em_analise', 'Em Analise')], default='ativo', max_length=20),
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(choices=[('drogas', '🚫 Drogas/Substâncias Ilícitas'), ('armas', '🔫 Armas e Munições'), ('falsificacao', '⚠️ Produto Contrafeito'), ('fraude', '💰 Fraude/Engano'), ('spam', '📧 Spam/Publicidade Indevida'), ('outros', '📌 Outros')], max_length=20)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', '⏳ Pendente'), ('em_analise', '🔍 Em Análise'), ('aprovado', '✅ Aprovado'), ('rejeitado', '❌ Rejeitado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('denunciante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('transacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transacao')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_criacao'],
                'unique_together': {('cliente', 'transacao')},
            },
        ),
    ]
