# Generated by Django 6.0.6 on 2026-07-07 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tentativalogin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=255)),
                ('nivel_risco', models.IntegerField(choices=[(1, 'Baixo'), (2, 'Médio'), (3, 'Alto'), (4, 'Crítico')], default=1)),
                ('eventos', models.IntegerField(default=0)),
                ('ultimo_evento', models.DateTimeField(blank=True, null=True)),
                ('coordenadas', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=255)),
                ('url_rtsp', models.URLField(blank=True, max_length=500, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('movimento', 'Movimento Detectado'), ('porta_aberta', 'Porta Aberta'), ('janela_aberta', 'Janela Aberta'), ('alarme', 'Alarme Disparado'), ('face_detectada', 'Face Detectada'), ('comportamento_suspeito', 'Comportamento Suspeito')], max_length=30)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
                ('alerta_enviado', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=10)),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventoseguranca')),
            ],
        ),
        migrations.CreateModel(
            name='SensorMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('pir', 'PIR'), ('ultrassom', 'Ultrassom'), ('laser', 'Laser')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_evento', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventoseguranca',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sensormovimento'),
        ),
    ]
