# Generated by Django 6.0.6 on 2026-07-08 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_zonarisco_camera_eventoseguranca_alerta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=255)),
                ('coordenadas', models.JSONField(default=dict)),
                ('populacao_estimada', models.IntegerField(default=0)),
                ('numero_residencias', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('roubo_residencia', 'Roubo a Residência'), ('roubo_veiculo', 'Roubo de Veículo'), ('assalto_pessoa', 'Assalto a Pessoa'), ('furto', 'Furto'), ('vandalismo', 'Vandalismo'), ('violencia_domestica', 'Violência Doméstica'), ('trafico_drogas', 'Tráfico de Drogas'), ('homicidio', 'Homicídio'), ('outro', 'Outro')], max_length=30)),
                ('descricao', models.TextField()),
                ('data_ocorrencia', models.DateTimeField()),
                ('localizacao', models.CharField(max_length=255)),
                ('coordenadas', models.JSONField(default=dict)),
                ('vitima', models.CharField(blank=True, max_length=100, null=True)),
                ('suspeito', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comunidade')),
                ('registado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstrategiaSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('policia_comunitaria', 'Polícia Comunitária'), ('vigilancia_vizinhos', 'Vigilância Rotativa entre Vizinhos'), ('camera_seguranca', 'Câmaras de Segurança'), ('iluminacao', 'Iluminação Pública'), ('alarme', 'Sistemas de Alarme'), ('guarda_patrimonial', 'Guarda Patrimonial'), ('grupo_whatsapp', 'Grupo de WhatsApp'), ('patrulha_voluntaria', 'Patrulha Voluntária'), ('outro', 'Outro')], max_length=30)),
                ('descricao', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('data_implementacao', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PercepcaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_seguranca', models.IntegerField(choices=[(1, 'Muito Inseguro'), (2, 'Inseguro'), (3, 'Neutro'), (4, 'Seguro'), (5, 'Muito Seguro')])),
                ('principais_medos', models.TextField()),
                ('sugestoes', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='faces/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioComunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
