# Generated by Django 6.0.6 on 2026-07-13 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fornecedor_total_avaliacoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermosAceitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(default='1.0', max_length=10)),
                ('aceite', models.BooleanField(default=True)),
                ('data_aceite', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_aceites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aceitação dos Termos',
                'verbose_name_plural': 'Aceitações dos Termos',
                'ordering': ['-data_aceite'],
            },
        ),
    ]
