# Generated by Django 6.0.7 on 2026-07-14 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_termosaceitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(max_length=100, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moeda', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', '⏳ Pendente'), ('success', '✅ Sucesso'), ('failed', '❌ Falhou'), ('refunded', '🔄 Reembolsado')], default='pending', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('ultimos_4_digitos', models.CharField(blank=True, max_length=4, null=True)),
                ('nome_cartao', models.CharField(blank=True, max_length=100, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('transacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_stripe', to='core.transacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_stripe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação Stripe',
                'verbose_name_plural': 'Transações Stripe',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
