# Generated by Django 6.0.7 on 2026-07-15 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transacaostripe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoEmola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', '⏳ Pendente'), ('success', '✅ Sucesso'), ('failed', '❌ Falhou')], default='pending', max_length=20)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('transacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_emola', to='core.transacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_emola', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação E-Mola',
                'verbose_name_plural': 'Transações E-Mola',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
